PAGE_WIDTH = 210
PAGE_HEIGHT = 297
MARGIN = 12
BODY_FONT_SIZE = 10
ORIGINAL_BODY_LINE_HEIGHT = 4.5
BODY_LINE_HEIGHT = ORIGINAL_BODY_LINE_HEIGHT
TEXT_SPACE = PAGE_WIDTH - 2 * MARGIN

BULLET_STR = "  •  "
BULLET_GAP = "     "

MINIMUM_FILL_FACTOR = 0.94